// Generated by CoffeeScript 1.3.3

/*
jQuery.values: get or set all of the name/value pairs from child input controls
based on http://stackoverflow.com/a/1490431/.
@argument data {array} If included, will populate all child controls.
@returns element if data was provided, or array of values if not
*/


(function() {

  $.fn.values = function(data) {
    var $els, $form;
    $form = $(this);
    if (typeof data !== 'object') {
      data = {};
      $els = $(':input:not(:disabled)', $form).get();
      $els.each(function() {
        switch (this.nodeName.toLowerCase()) {
          case "input":
            switch (this.type) {
              case "radio":
              case "checkbox":
                if (typeof data[this.name] === 'undefined') {
                  data[this.name] = [];
                }
                if (this.checked) {
                  data[this.name].push(this.value || '');
                }
                break;
              default:
                data[this.name] = this.value || '';
            }
            break;
          case "select":
          case "textarea":
            data[this.name] = this.value || '';
        }
      });
      return data;
    } else {
      $.each(data, function(key, value) {
        $(':input[name=' + key + ']', $form).val(value);
      });
      return $form;
    }
  };

}).call(this);
